### ISSUE TITLE
Crash when Immersive Engineering is not installed

### ISSUE THREAD

**Issue by WenXin20** [gisellevonbingen-Minecraft/MineColonies_Compatibility#2]
Minecolonies Compat v2.2

The game crashes since Immersive Engineering is not installed. I assume the mod is optional?

```
[03May2024 20:44:12.943] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: minecolonies_compatibility, class steve_gall.minecolonies_compatibility.core.common.MineColoniesCompatibility
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/tool/BulletHandler$IBullet
	at steve_gall.minecolonies_compatibility.core.common.module.ModuleManager.<clinit>(ModuleManager.java:32) ~[MineColonies_Compatibility-1.20.1-2.2.jar%23780!/:1.20.1-2.2]
	at steve_gall.minecolonies_compatibility.core.common.MineColoniesCompatibility.<init>(MineColoniesCompatibility.java:43) ~[MineColonies_Compatibility-1.20.1-2.2.jar%23780!/:1.20.1-2.2]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.20.jar%23956!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23955!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.tool.BulletHandler$IBullet
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 16 more
```

**Comment by gisellevonbingen** [comment]
Oops, I will fix this in few hours.

**Comment by gisellevonbingen** [comment]
Fixed, Thanks for report !

**Comment by WenXin20** [comment]
Thanks!
