### ISSUE TITLE
[CrashOnLoad] When using latest LetsDo Vinery

### ISSUE THREAD

**Issue by drakray** [gisellevonbingen-Minecraft/MineColonies_Compatibility#63]
https://pastebin.com/gq2Mf80x
Minecraft 1.20.1
Forge 47.3.12
MineColonies 1.1.774
MineColoniesCompat 2.46
MineColoniesTweaks 2.39
MineColoniesLetsDo 1.7
LetsDo Vinery 1.4.33
ManyOtherMods™

<details><summary>Snippets</summary>

```
	Suppressed: net.minecraftforge.fml.ModLoadingException: Compatibility addon for MineColonies (minecolonies_compatibility) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: net/satisfy/vinery/registry/RecipeTypesRegistry
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:125) ~[javafmllanguage-1.20.1-47.3.12.jar%231160!/:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[fmlcore-1.20.1-47.3.12.jar%231159!/:?] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}

```

```
	Caused by: java.lang.NoClassDefFoundError: net/satisfy/vinery/registry/RecipeTypesRegistry
		at steve_gall.minecolonies_compatibility.module.common.lets_do_vinery.init.ModuleCraftingTypes.lambda$static$0(ModuleCraftingTypes.java:16) ~[minecolonies-compatibility-1.20.1-2.46.jar%231111!/:1.20.1-2.46] {re:classloading}
		at steve_gall.minecolonies_tweaks.api.registries.DeferredRegisterHelper.lambda$registerCraftingType$5(DeferredRegisterHelper.java:127) ~[minecolonies-tweaks-1.20.1-2.39.jar%231119!/:1.20.1-2.39] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.lambda$addEntries$1(DeferredRegister.java:386) ~[forge-1.20.1-47.3.12-universal.jar%231163!/:?] {re:classloading}

```

```
	Caused by: java.lang.ClassNotFoundException: net.satisfy.vinery.registry.RecipeTypesRegistry
		at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
		at steve_gall.minecolonies_compatibility.module.common.lets_do_vinery.init.ModuleCraftingTypes.lambda$static$0(ModuleCraftingTypes.java:16) ~[minecolonies-compatibility-1.20.1-2.46.jar%231111!/:1.20.1-2.46] {re:classloading}
		at steve_gall.minecolonies_tweaks.api.registries.DeferredRegisterHelper.lambda$registerCraftingType$5(DeferredRegisterHelper.java:127) ~[minecolonies-tweaks-1.20.1-2.39.jar%231119!/:1.20.1-2.39] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.lambda$addEntries$1(DeferredRegister.java:386) ~[forge-1.20.1-47.3.12-universal.jar%231163!/:?] {re:classloading}

```

</details>

**Comment by drakray** [comment]
never mind all that, I didn't get the latest MineColoniesCompat  -_-'
My bad
